import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {JSDOM} from 'jsdom';

const html=readFileSync('index.html','utf8');
const script=readFileSync('saved-aircraft.js','utf8');
const dom=new JSDOM(html,{url:'https://joshuamaziarz1-ux.github.io/-jacks-flight-tracker/',runScripts:'outside-only'});
const w=dom.window;
w.eval('const input=document.getElementById("tailInput");function begin(tail){window.__lastTail=tail;}');
w.eval(script);
const id=name=>w.document.getElementById(name);
const initial=JSON.parse(w.localStorage.getItem('jft.saved.aircraft.v1'));
assert.equal(initial.categories[0].name,'Sweet Aviation');
assert.deepEqual(initial.planes.map(p=>p.tail),['N233ND','N278DC']);
assert.equal(id('libraryPlanes').children.length,2,'two seeded aircraft appear');
assert.ok(id('libraryTabs').textContent.includes('Sweet Aviation'));
id('categoryName').value='Family Favorites';
id('newCategoryForm').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
let library=JSON.parse(w.localStorage.getItem('jft.saved.aircraft.v1'));
const custom=library.categories.find(c=>c.name==='Family Favorites');
assert.ok(custom,'category created');
assert.equal(id('categoryManager').textContent.includes('Family Favorites'),true);
id('tailInput').value='N12345';
id('saveCategory').value=custom.id;
id('saveCurrent').click();
library=JSON.parse(w.localStorage.getItem('jft.saved.aircraft.v1'));
assert.equal(library.planes.find(p=>p.tail==='N12345').categoryId,custom.id);
assert.ok(id('libraryPlanes').textContent.includes('N12345'));
const track=Array.from(id('libraryPlanes').querySelectorAll('button')).find(x=>x.textContent==='Track');
track.click();
assert.equal(w.__lastTail,'N12345','saved plane can be tracked');
const move=id('libraryPlanes').querySelector('select');
move.value='sweet-aviation';
move.dispatchEvent(new w.Event('change',{bubbles:true}));
library=JSON.parse(w.localStorage.getItem('jft.saved.aircraft.v1'));
assert.equal(library.planes.find(p=>p.tail==='N12345').categoryId,'sweet-aviation');
const domReload=new JSDOM(html,{url:'https://joshuamaziarz1-ux.github.io/-jacks-flight-tracker/',runScripts:'outside-only'});
const previous=w.localStorage.getItem('jft.saved.aircraft.v1');
domReload.window.localStorage.setItem('jft.saved.aircraft.v1',previous);
domReload.window.eval('const input=document.getElementById("tailInput");function begin(tail){}');
domReload.window.eval(script);
assert.equal(JSON.parse(domReload.window.localStorage.getItem('jft.saved.aircraft.v1')).planes.length,3);
console.log('PASS: seeded planes, add category, save, track, move, persist after reload');
